name: Trovu
description: "Trovu, never forget your fake booking"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_theme: ^6.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.1
  intl: ^0.19.0
  carousel_slider_plus: ^6.0.0
  supabase_flutter: ^2.5.11
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  openfoodfacts: ^3.12.0
  flutter_barcode_scanner: ^2.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/theme.json
    - assets/images/trovu_classic.png
    - assets/images/trovu_transparent.png
    - assets/images/trovu_background.png
    - assets/images/trovu_black.png
    - assets/images/google.png
    - assets/images/scroll.gif
    - assets/images/basket_gif.gif
    - assets/trovu_icon.png
